name: Backend CI/CD

on:
  push:
    branches: [ main ]
    
permissions:
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Calculate version
      id: version
      run: |
        # Get the latest tag
        latest_tag=$(git describe --tags --abbrev=0 --match "backend-v*" 2>/dev/null || echo "backend-v0.0.0")
        # Increment patch version
        current_version=${latest_tag#backend-v}
        IFS='.' read -r major minor patch <<< "$current_version"
        new_patch=$((patch + 1))
        new_version="v$major.$minor.$new_patch"
        echo "new_version=$new_version" >> $GITHUB_OUTPUT
        
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build and push backend
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: |
          thabelo/quotes-backend:latest
          thabelo/quotes-backend:${{ steps.version.outputs.new_version }}
        cache-from: type=registry,ref=thabelo/quotes-backend:buildcache
        cache-to: type=registry,ref=thabelo/quotes-backend:buildcache,mode=max

    - name: Create and push git tag
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'github-actions@github.com'
        git tag backend-${{ steps.version.outputs.new_version }}
        git push origin backend-${{ steps.version.outputs.new_version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}